String x = "X";
String yes = "YES";
String no = "NO";
String question = "Are you sure that you want";
String question2 = "to close this window?";

void Population() {
  //float centerX = appWidth * 1/2; //point
  //float centerY = appHeight * 1/2; //point
  //quiteButtonX = centerX - ( appWidth * 1/4 ); 
  //quitButtonY = centerY - ( appHeight * 1/4 ); 
  //quitButtonWidth = appWidth * 1/2; //Line not point, thus use formula
  //quitButtonHeight = appHeight * 1/2; //Line not point, thus use formula
  textX = appWidth * 18.7/20;
  textY = appHeight * 1.4/20;
  font = createFont("Algerian", 55);
  quiteButtonX = appWidth * 18/20; 
  quitButtonY = appHeight * 0/4; 
  quitButtonWidth = appWidth * 2/20;
  quitButtonHeight = appHeight * 2/20;
  quitX = appWidth * 18.55/20;
  quitY = appHeight * 0.5/20;
  quitWidth = appWidth * 1/20;
  quitHeight = appHeight * 1/20;
  textSize = appHeight/10;  
  areYouSureX = appWidth/4;
  areYouSureY = appHeight/4;
  areYouSureWidth = appWidth/2;
  areYouSureHeight = appHeight/3;
  yesX = appWidth * 5/20;
  yesY = appHeight * 8.7/20;
  yesWidth = appWidth * 5/20;
  yesHeight = appHeight * 2.97/20;
  noX = appWidth * 10/20;
  noY = appHeight * 8.7/20;
  noWidth = appWidth * 5/20;
  noHeight = appHeight * 2.97/20;
  questionX = appWidth * 1/4;
  questionY = appHeight * 1.25/5;
  questionWidth = appWidth * 10/20;
  questionHeight = appHeight * 3.7/20;
  textX2 = appWidth * 5.5/20;
  textY2 = appHeight * 6.8/20;
  textX3 = appWidth * 6.5/20;
  textY3 = appHeight * 7.5/20;
  textX4 = appWidth * 6.78/20;
  textY4 = appHeight * 10.45/20;
  textX5 = appWidth * 19/20;
  textY5 = appHeight * 10.45;
} //End Population
